### ISSUE TITLE
possible redundant code found in style.css

### ISSUE THREAD

**Issue by ktriggsdev** [MrAshwin2142/The-Wall-of-Projects#65]
Hi, when adding comments to the `style.css` file, I found what appeared to be redundant code, I wanted to check if this code is supposed to be there or if it should be removed?
```css
.starContributor {
  min-width: 15rem;
  display: flex;
  flex-direction: column;
  font-size: 0.8em;
  padding: 0.6rem;
}

/* sets h4 element with class of starContributor  to have a margin-bottom of 1rem */
.starContributor h4 {
  margin-bottom: 1.5rem;
}

/*-----Table container-----*/

/* 
not sure if this code is redundant or not
 */
.starContributor {
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  margin: 20px;
}
```
